### ISSUE TITLE
Code review issues

### ISSUE THREAD

**Issue by MatanBobi** [franco-ortega/hide-and-seek#30]
Hi Franco! :)
Here are the stuff I saw:
1. I know that CRA comes with `testing-library` in the dependencies but it should be a devDependency since we don't need that in our production bundle :)
https://github.com/franco-ortega/hide-and-seek/blob/main/package.json#L6
2. I highly recommend using [Prettier](https://prettier.io/) for code formatting. It's an amazing tool that formats your indentation, removes unnecessary line breaks and much more. Give it a try, it does it automatically once configured :)
3. https://github.com/franco-ortega/hide-and-seek/blob/main/src/utils/utils.js#L4
Since there's no way the `difficulty` in the param will be more than one, you can do something like this for a cleaner code:
```
const boxCount = (difficulty) => {
  if(difficulty === 'easy') return 3;
  if(difficulty === 'medium') return 4;
  if(difficulty === 'hard') return 8;

  return 0;
};
```
If you don't want to go with this one, you should go with an `if` and `else if` since difficulty can only be one of these options.
4. I really recommend you don't use constant strings lying around in the code. This can easily cause bugs if you have typos.
It's best to create a constant that serves as an enum in this case:
```
const DIFFUCLITY_LEVELS = {
  EASY: 'easy',
  MEDIUM: 'medium',
  HARD: 'hard'
}
```
And everytime you need it, you'll just import this const.
5. https://github.com/franco-ortega/hide-and-seek/blob/main/src/utils/utils.js#L15
https://github.com/franco-ortega/hide-and-seek/blob/main/src/components/App/App.jsx#L12
`module.exports` is the `requirejs` approach. In the browser you can use `ESModules` so you can just write `export const boxCount = (difficulty) => {}` and you'll get the function exported :)
6. https://github.com/franco-ortega/hide-and-seek/blob/main/src/components/App/App.jsx#L15
I'm not sure why you need this hook to be defined here since only one route uses it. Try to co-locate the state to only where it's needed or you'll cause unnecessary renders to your app. You can read more about it [here](https://kentcdodds.com/blog/state-colocation-will-make-your-react-app-faster).

These are the points I saw for now but I only covered these files and not all of them because there's a lot of code, but I did see some stuff worth covering.
I usually suggest code reviews from time to time in my twitter account so we can give this one another round next time :)
Hope this is helpful :)

**Comment by franco-ortega** [comment]
Thank you again so much for all this. I appreciate the effort and advice.

1. Interesting. I guess it's not possible for the install to add some React scripts to the dependencies and other React scripts to the devDependencies? I guess everything has to go into the same category when it is installed.

2. I've heard mixed reviews about Prettier. Maybe I'll try it on a sample project to see for myself.

3. I like this approach. It does look cleaner. Although, why would there be an option for it to `return 0`? I wouldn't want it to return a 0 value. And I believe that functions don't need a return statement to work. If anything, might it be better to return an error message if none of the `if statements` are triggered?

4. I've heard a little about enums. Your recommendation inspired me to do some research about them. Now I have a better understanding of their use, and how they don't really exist in JavaScript, ha, and the problems they can cause in JavaScript. But I don't think I need to worry about these problems in my use case for this app. Also, I saw another place in my app where an enum would be even more useful, so I added one there too.

5. Gotcha. That makes sense. Making this change caused an eslint error, but the console/terminal also informed me to just add "type": "module" to my eslint file, and that fixed it.

6. I don't know which state hook you were talking about. I did a bunch of refactoring over the weekend before looking at this issue, and there is no longer any code on the highlighted line. But all the remaining state hooks do get passed into multiple components.

Thank you again for all the help!

**Comment by MatanBobi** [comment]
I'm glad I was able to help Franco!
1. I know that they had an issue with that which was fixed, I'll try to create a PR to fix that.
2. I actually haven't heard someone who's using prettier and not satisfied :)
3. Yeah, the 0 was just because I didn't want to change the function's signature (if it returns a number, it should return a number), you can throw an error and handle it.
4. Glad you liked this one :)
5. Yep :)
6. Then I guess you fixed that one..

Have a great day Franco!
